# Generated by Django 2.2.1 on 2019-06-03 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1111111), django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
