# Generated by Django 2.2.1 on 2019-06-03 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190603_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='celular',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(111111111), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
