# Generated by Django 2.2.1 on 2019-06-03 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20190603_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([0-9]){13}', 'Your string should contain letter A in it.')]),
        ),
    ]
