# Generated by Django 2.2.1 on 2019-06-03 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_auto_20190603_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([0-9]){13}', 'NIT debe ser numerico de 13 caracteres')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='celular',
            field=models.TextField(validators=[django.core.validators.RegexValidator('([0-9]){13}', 'campo numerico de 10 digitos')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('([0-9]){7}', 'campo numerico de 7 digitos')]),
        ),
    ]
