# Generated by Django 2.2.1 on 2019-06-03 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_auto_20190603_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='celular',
            field=models.TextField(validators=[django.core.validators.RegexValidator('([0-9]){10}', 'campo numerico de 10 digitos')]),
        ),
    ]
