# Generated by Django 2.2.1 on 2019-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_auto_20190603_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], max_length=1),
        ),
    ]
