# Generated by Django 2.2.1 on 2019-06-03 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre', '0006_auto_20190602_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torre',
            name='numero_pisos',
            field=models.TextField(max_length=1, validators=[django.core.validators.RegexValidator('([0-9]){1}', 'campo numerico de 1 digito')]),
        ),
    ]
