# Generated by Django 2.2.1 on 2019-06-02 23:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torre', '0006_auto_20190602_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('torre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torre.Torre')),
            ],
        ),
    ]
