# Generated by Django 2.2.1 on 2019-06-02 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
