# Generated by Django 2.2.1 on 2019-06-03 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0003_apartamento_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='numero_apartamento',
            field=models.TextField(max_length=3, validators=[django.core.validators.RegexValidator('([0-9]){3}', 'campo numerico de 3 digitos')]),
        ),
    ]
