# Generated by Django 2.2.1 on 2019-06-03 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='celular',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('([0-9]){10}', 'campo numerico de 10 digitos')]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_identificacion',
            field=models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]{8,11}', 'campo numerico de almenos 8 digitos max 11')]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono1',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('([0-9]){7}', 'campo numerico de 7 digitos')]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono2',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator('([0-9]){7}', 'campo numerico de 7 digitos')]),
        ),
    ]
