# Generated by Django 2.2.1 on 2019-06-03 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0003_auto_20190603_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='apellidos',
            field=models.TextField(max_length=45, validators=[django.core.validators.RegexValidator('([A-Z])\\w+', 'campo solo admite letras')]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombres',
            field=models.TextField(max_length=45, validators=[django.core.validators.RegexValidator('([A-Z])\\w+', 'campo solo admite letras')]),
        ),
    ]
