# Generated by Django 2.2.1 on 2019-06-03 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0004_auto_20190603_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='numero_identificacion',
            field=models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('([0-9]){8,11}', 'campo numerico de almenos 8 digitos max 11')]),
        ),
    ]
